# Generated by Django 4.2.1 on 2023-06-12 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('exam_date', models.DateField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='studentinfo',
            options={},
        ),
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='details.studentinfo')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='details.subject')),
            ],
            options={
                'verbose_name_plural': 'Student Info',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.studentinfo'),
        ),
    ]
