# Generated by Django 4.2.1 on 2023-06-12 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_exam_examinfo_remove_subjectassignment_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='examinfo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='examinfo',
            name='exam_date',
        ),
        migrations.RemoveField(
            model_name='examinfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='examinfo',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='examinfo',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='examinfo',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='examinfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='examinfo',
            name='uuid',
        ),
        migrations.AddField(
            model_name='examinfo',
            name='studentinfo_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='details.studentinfo'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.AddField(
            model_name='examinfo',
            name='Subjects',
            field=models.ManyToManyField(to='details.subject'),
        ),
    ]
