# Generated by Django 4.2.1 on 2023-06-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_subject_remove_examinfo_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_ticket_number', models.CharField(max_length=100, unique=True)),
                ('exam_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='ExamInfo',
        ),
        migrations.DeleteModel(
            name='StudentInfo',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
