# Generated by Django 4.2.1 on 2023-06-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_hallticket_delete_examinfo_delete_studentinfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallticket',
            name='hall_ticket_number',
        ),
        migrations.AddField(
            model_name='hallticket',
            name='student_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
